print(76+56) #addition

print(100-70)#subtraction

print(30*80) #multiplication

print(1566/3) #division

print(100//3) #floordivision(the output will be the number before decimal point after dividing)

print(625%5) #modulus( it shows remainder)

a=300

a+=500 #it is same as a=a+5

print(a)

a-=200 #it is same as a=a-200

print(a)

a*=50 # it is same as a=a*50

print(a)

a/=60 # it is same as a/60

print(a)

a%=77 #it is same as a%77

print(a)

a//=96 #it is same as a=a//96

print(a)

a**=45 # is same as a**45

print(a)

#expotential

x=50
y=78
print(x**y) #this means 50 multiply 78 times

x=2
y=3
print(x**y) #this means 2*2*2


print(5==6)#equal

print(55!=66) # notequal

print(46>34) #greaterthan

print(78<98) #lessthan

print(34>=56) #greater thanm equal

print(45<=90) #lessthan equal

##logical operators##

x=500

print(x<679 and x<890) #and opertor returns true if both statements are true

print(x<678 and x>789)

print(x<678 or x>568) #or operator return if anyone condition is true or false

print(x<78 or x>600)

print(not(x<678 and x<890)) #reverse the condition  i.e.. if its true its print false
